from __future__ import annotations

import json
from typing import Optional

from .. import settings
from ..models import Case, Verdict
from ..store.storage import Store
from ..agents.tools import ToolContext


class ReportBuilder:
    """Writes human-readable investigation reports (markdown + JSON) per case."""

    def __init__(self, store: Store):
        self.store = store

    def write(self, case: Case, verdict: Verdict, ctx: ToolContext) -> str:
        md = self.render_markdown(case, verdict)
        settings.REPORT_DIR.mkdir(parents=True, exist_ok=True)
        md_path = settings.REPORT_DIR / f"{case.id}.md"
        json_path = settings.REPORT_DIR / f"{case.id}.json"
        md_path.write_text(md)
        json_path.write_text(json.dumps(verdict.model_dump(mode="json"), indent=2, default=str))
        return str(md_path)

    def render_markdown(self, case: Case, verdict: Verdict) -> str:
        L: list[str] = []
        L.append(f"# Investigation Report — {case.id}")
        L.append("")
        L.append(f"**{case.title}**  ")
        L.append(f"Window: `{case.window_start.isoformat()}` → `{case.window_end.isoformat()}`")
        L.append("")
        L.append(f"## Verdict: **{verdict.disposition.value}** · severity "
                 f"`{verdict.severity.value}` · confidence {verdict.confidence:.0%} "
                 f"({verdict.model})")
        L.append("")
        L.append(verdict.summary)
        if verdict.notes:
            L.append("")
            L.append(f"> Notes: {verdict.notes}")
        L.append("")
        L.append("## How it was investigated")
        L.append("")
        L.append(verdict.investigation_summary)
        L.append("")
        L.append("## Entities")
        L.append("")
        L.append(f"- Users: {', '.join(case.entities.users) or '-'}")
        L.append(f"- IPs: {', '.join(case.entities.ips) or '-'}")
        L.append(f"- Hosts: {', '.join(case.entities.hosts) or '-'}")
        L.append("")
        L.append("## MITRE ATT&CK relevance")
        L.append("")
        for tid in verdict.mitre_relevance:
            L.append(f"- `{tid}`")
        L.append("")
        L.append("## Indicators of compromise")
        L.append("")
        L.append("| type | value |")
        L.append("|------|-------|")
        for ind in verdict.indicators:
            L.append(f"| {ind.get('type', '')} | {ind.get('value', '')} |")
        L.append("")
        L.append("## Recommended actions")
        L.append("")
        for act in verdict.recommended_actions:
            gate = "🔒 human approval" if act.requires_approval else "auto-safe"
            L.append(f"- **{act.action}** ({gate})  ")
            L.append(f"  {act.description}")
        L.append("")
        L.append("## Evidence timeline")
        L.append("")
        for item in verdict.timeline:
            detail = "; ".join(f"{k}={v}" for k, v in item.get("detail", {}).items())[:160]
            L.append(f"- `{item['time']}` **{item['source']}/{item['event_type']}** "
                     f"`{item.get('actor', '')} → {item.get('target', '')}` {detail}")
        L.append("")
        L.append("## Agent tool trace")
        L.append("")
        for call in verdict.tool_trace:
            out = call.output.replace("\n", " ")[:240]
            L.append(f"{call.step}. `{call.tool}` {json.dumps(call.input, default=str)[:200]}  ")
            L.append(f"   → {out}")
        L.append("")
        L.append("---")
        L.append("Generated by the AI Alert Triage Agent. Evidence-based, auditable, human-reviewable.")
        return "\n".join(L)